ga4:
  property_id: "xxx"
  key_file: "Dateipfad"

export:
  start_date: "2025-01-01"
  end_date: "2025-12-31"

  events:
    - "view_item"
    - "add_to_cart"
    - "begin_checkout"
    - "purchase"

  output_folder: "data"
