ga4:
  property_id: xxxxxxxxx
  key_file: "path/to/your/service-account.json"

export:
  start_date: '2025-11-01'
  end_date: '2025-11-30'

  events:
    - view_item
    - add_to_cart
    - begin_checkout
    - purchase

  output_folder: 'data'
