ga4:
  property_id: "513248392"
  key_file: "C:\Users\psp\Documents\siete-marketing-analytics"

export:
  start_date: "2024-10-01"
  end_date: "2024-10-31"

  events:
    - "view_item"
    - "add_to_cart"
    - "begin_checkout"
    - "purchase"

  output_folder: "data"
